karpenter:
  serviceAccount:
    create: false
  nodeSelector:
    kubernetes.io/os: linux
  settings:
    aws:
      clusterName:
      clusterEndpoint:
      defaultInstanceProfile:
      interruptionQueueName:
  controller:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 150Mi
