serviceAccount:
  create: false

resources:
  limits:
    cpu: 1
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector:
  type: karpenter
tolerations:
  - effect: NoSchedule
    key: lt-1d-expiry
    value: "true"
